import Image from 'next/image';
import Link from 'next/link';
import {CTA,Eyebrow,ResumeButton,Reveal,SectionHeading,Stats} from '@/components/shared';
import {Icon,type IconName} from '@/components/icons';
import {StoryButton} from '@/components/story';
import {Skills} from '@/components/skills';
import {pageMetadata} from '@/lib/seo';
export const metadata=pageMetadata('About','The story, skills, education and interests of Subrahmanyam Srighakollapu, a full-stack developer and independent freelancer.','/about/');
const story:{title:string;text:string;icon:IconName;color:string}[]=[{title:'Curiosity',text:'Started my journey with a strong interest in technology and problem solving.',icon:'idea',color:'orange'},{title:'Learning',text:'Explored different technologies, built projects and gained hands-on experience.',icon:'book',color:'mint'},{title:'Building',text:'Worked on professional and freelance projects across various domains, delivering real solutions.',icon:'code',color:'blue'},{title:'Now',text:'Continuing to learn, build and grow, aiming to create bigger and more impactful products.',icon:'rocket',color:'purple'}];
const values:{title:string;text:string;icon:IconName;color:string}[]=[{title:'Build Impactful Products',text:'Solve real-world problems with technology.',icon:'target',color:'pink'},{title:'Work with Great Teams',text:'Collaborate, learn and grow together.',icon:'users',color:'blue'},{title:'Keep Learning',text:'Always explore new technologies and ideas.',icon:'sparkles',color:'orange'},{title:'Create Better Experiences',text:'Focus on clean, intuitive and user-friendly solutions.',icon:'heart',color:'pink'}];
const education:{date:string;title:string;school:string;result?:string;icon:IconName;color:string}[]=[{date:'2021 – 2025',title:'B.Tech - Electronics & Communication Engineering (ECE)',school:'RGUKT Srikakulam, Etcherla, Srikakulam',result:'CGPA: 8.9',icon:'education',color:'cyan'},{date:'Apr 2022 – Ongoing',title:'Industry Ready Certification in Full-Stack Development',school:'NxtWave Disruptive Technologies',icon:'award',color:'purple'},{date:'2019 – 2021',title:'Intermediate - MPC (Mathematics, Physics, Chemistry)',school:'RGUKT Srikakulam, Etcherla, Srikakulam',result:'CGPA: 9.35',icon:'book',color:'mint'},{date:'2018 – 2019',title:'Secondary School Certificate (SSC)',school:'ZPP High School, Vanapalli, Kothapeta Mandal',result:'CGPA: 10.0',icon:'award',color:'orange'}];
const hobbies:{name:string;image:string;text:string;icon:IconName;color:string}[]=[{name:'Gaming',image:'gaming',text:'Love exploring story-based games.',icon:'game',color:'blue'},{name:'Traveling',image:'travel',text:'Exploring new places and cultures.',icon:'plane',color:'cyan'},{name:'Photography',image:'photography',text:'Capturing moments and nature.',icon:'camera',color:'orange'},{name:'Learning',image:'learning',text:'Always curious to learn new things.',icon:'book',color:'pink'}];
export default function About(){return <>
  <section className="about-hero"><div className="container about-hero-grid"><div className="about-hero-copy"><Eyebrow>About me</Eyebrow><h1>Turning Ideas<br/>Into Real<br/><span className="gradient-text purple-gradient">Digital Products</span></h1><p>I’m Subrahmanyam Srighakollapu, a Full-Stack Developer with a passion for building web applications, solving real-world problems and creating digital experiences that make an impact.</p><div className="button-row"><ResumeButton className="button button-dark"/><StoryButton light/></div><Stats compact/></div><div className="about-hero-art"><span className="handwritten" aria-hidden="true">Code<br/>Design<br/>Develop<br/>Repeat ⤵</span><div className="about-hero-photo" data-parallax><Image src="/images/about-portrait.webp" alt="Subrahmanyam seated at his laptop in a creative workspace" fill sizes="(max-width:700px) 90vw, 48vw" priority/></div><div className="about-hero-badge"><Icon name="code" size={34}/><span>Passionate about building products that solve real problems.</span></div></div></div></section>
  <section className="story-section dark-section"><div className="container story-grid"><Reveal><Eyebrow dark>My story</Eyebrow><h2>A Journey of<br/><span className="gradient-text">Learning, Building</span><br/>and Growing</h2><p>From a curious student to a Full-Stack Developer, my journey has always been about exploring new technologies, solving challenges and building meaningful digital products. I enjoy turning ideas into real-world solutions that create value for users and businesses.</p></Reveal><div className="story-timeline">{story.map((s,i)=><Reveal key={s.title} className="story-timeline-item" delay={i*60}><span className={`icon-tile ${s.color}`}><Icon name={s.icon} size={27}/></span><div><h3>{s.title}</h3><p>{s.text}</p></div></Reveal>)}</div></div></section>
  <section className="section values-section"><div className="container values-grid"><Reveal><Eyebrow>What drives me</Eyebrow><h2>Problem Solving<br/>Through Technology</h2><p>I enjoy working on challenging problems, exploring new technologies and building products that make people’s lives easier. Whether it’s a complex application, a clean UI or an efficient backend system, I’m always excited to learn and improve.</p><Link className="button" href="/contact/">Let’s Connect<Icon name="arrow"/></Link></Reveal><div className="values-cards">{values.map((v,i)=><Reveal className="value-card" key={v.title} delay={i*55}><span className={`icon-tile ${v.color}`}><Icon name={v.icon} size={28}/></span><h3>{v.title}</h3><p>{v.text}</p></Reveal>)}</div></div></section>
  <section id="skills" className="section about-skills"><div className="container"><SectionHeading eyebrow="Technical skills" title="Technologies I Work With" description="A combination of modern frontend, backend, database and deployment tools to build scalable and high-performance applications."/><Reveal><Skills/></Reveal></div></section>
  <section className="section education-section"><div className="container education-layout"><div><SectionHeading eyebrow="Education" title="My Academic Journey"/><div className="education-timeline">{education.map((e,i)=><Reveal className="education-row" key={e.title} delay={i*50}><span className={`icon-tile ${e.color}`}><Icon name={e.icon} size={26}/></span><time>{e.date}</time><div><h3>{e.title}</h3><p>{e.school}</p>{e.result&&<p>{e.result}</p>}</div></Reveal>)}</div></div><Reveal className="certifications"><Eyebrow>Certifications</Eyebrow><div className="certificate"><span className="icon-tile navy"><Icon name="terminal" size={28}/></span><div><h3>Developer Foundation<br/>(Git, Command Line)</h3><p>NxtWave</p></div><small>2022</small></div><div className="certificate"><img src="/tech/python.svg" width="40" height="40" alt="" loading="lazy"/><div><h3>Programming Foundations<br/>with Python</h3><p>NxtWave</p></div><small>2022</small></div><blockquote><Icon name="quote" size={30}/><p>Continuous learning and practical experience have always been the key drivers in my journey.</p></blockquote></Reveal></div></section>
  <section className="section hobbies-section"><div className="container"><SectionHeading eyebrow="Beyond work" title="Things I Enjoy" description="When I’m not coding, you can find me exploring new places, playing games or capturing moments."/><div className="hobbies-grid">{hobbies.map((h,i)=><Reveal className="hobby-card" key={h.name} delay={i*70}><div className="hobby-photo"><Image src={`/images/${h.image}.webp`} alt={h.name==='Traveling'?'Mountain landscape':h.name==='Gaming'?'Game controller':h.name==='Photography'?'Camera in a mountain landscape':'Books in a reading space'} fill sizes="(max-width:600px) 50vw, 25vw"/></div><div><span className={`icon-tile ${h.color}`}><Icon name={h.icon} size={24}/></span><div><h3>{h.name}</h3><p>{h.text}</p></div></div></Reveal>)}</div></div></section><CTA/>
  </>;}
