import Image from 'next/image';
import {profile} from '@/data/portfolio';
import {CTA,Eyebrow,Reveal} from '@/components/shared';
import {Icon,type IconName} from '@/components/icons';
import {ContactForm,ContactInfo} from '@/components/contact';
import {pageMetadata} from '@/lib/seo';
export const metadata=pageMetadata('Contact','Contact Subrahmanyam Srighakollapu for full-time opportunities, freelance development projects and technology collaborations.','/contact/');
const contactFeatures:{label:string;icon:IconName;color:string}[]=[{label:'Quick Response',icon:'message',color:'purple'},{label:'Open to Opportunities',icon:'users',color:'blue'},{label:'Freelance Projects',icon:'handshake',color:'mint'},{label:'Tech Discussions',icon:'idea',color:'orange'}];
const direct:{title:string;text:string;icon:IconName;color:string;href:string}[]=[{title:'Send an Email',text:'Get a detailed response about your project or opportunity.',icon:'mail',color:'blue',href:`mailto:${profile.email}`},{title:'Let’s Have a Call',text:'Discuss your requirements directly over a call.',icon:'message',color:'mint',href:`tel:${profile.phoneHref}`},{title:'Schedule a Meeting',text:'Email me to find a time that works for us.',icon:'calendar',color:'purple',href:`mailto:${profile.email}?subject=Let%27s%20schedule%20a%20meeting`}];
export default function Contact(){return <><section className="contact-hero"><div className="contact-hero-art" data-parallax><Image src="/images/contact-desk.webp" alt="A sunlit workspace with a laptop, plants, notebook and a black coffee mug" fill sizes="(max-width:700px) 100vw, 55vw" priority/></div><div className="container"><div className="contact-hero-copy"><Eyebrow>Get in touch</Eyebrow><h1>Let’s Build<br/>Something Amazing<br/><span className="gradient-text purple-gradient">Together</span></h1><p>I’m always open to new opportunities, interesting projects or just a friendly chat about technology, ideas or collaboration. Feel free to reach out — I’ll get back to you as soon as possible.</p><div className="contact-features">{contactFeatures.map(f=><div key={f.label}><span className={`icon-tile ${f.color}`}><Icon name={f.icon} size={25}/></span><span>{f.label}</span></div>)}</div></div></div><span className="handwritten contact-hero-note" aria-hidden="true">Ideas<br/>Code<br/>Design<br/>Deploy<br/>Repeat ⤵</span></section>
  <section className="section contact-main"><div className="container"><div className="contact-columns"><Reveal className="contact-panel message-panel"><Eyebrow>Send a message</Eyebrow><h2>Drop Me a Message</h2><p>Have a project in mind, a job opportunity or just want to say hello? Fill out the form and I’ll get back to you soon.</p><ContactForm/></Reveal><div className="contact-right"><Reveal className="contact-panel information-panel"><Eyebrow>Contact information</Eyebrow><h2>Let’s Connect</h2><p>Here are the different ways you can reach me.</p><ContactInfo/></Reveal><Reveal className="contact-panel available-panel"><Eyebrow>Currently available for</Eyebrow><div><span className="availability-dot"/><div><h3>Open to Opportunities</h3><p>I’m currently available for full-time opportunities, freelance projects and interesting collaborations.</p></div><span className="icon-tile"><Icon name="calendar" size={25}/></span></div></Reveal></div></div><div className="contact-bottom-grid"><Reveal className="contact-panel location-panel"><Eyebrow>Find me here</Eyebrow><a className="map-link" href="https://www.google.com/maps/search/?api=1&query=Andhra+Pradesh+India" target="_blank" rel="noopener noreferrer" aria-label="View Andhra Pradesh, India on Google Maps"><Image src="/images/location.webp" alt="Map highlighting Andhra Pradesh, India" fill sizes="(max-width:700px) 90vw, 30vw"/><span className="icon-button"><Icon name="external" size={18}/></span></a></Reveal><Reveal className="contact-panel direct-panel"><Eyebrow>Prefer to connect directly?</Eyebrow>{direct.map(d=><a className="direct-option" href={d.href} key={d.title}><span className={`icon-tile ${d.color}`}><Icon name={d.icon} size={25}/></span><span><strong>{d.title}</strong><small>{d.text}</small></span><Icon name="arrow" size={18}/></a>)}</Reveal><Reveal className="contact-panel stay-connected"><Eyebrow>Social links</Eyebrow><h2>Let’s Stay Connected</h2><p>Follow me on these platforms to see my latest projects, updates and tech content.</p>{[{name:'GitHub',icon:'github' as IconName,text:'View my code, projects and contributions.',href:profile.github},{name:'LinkedIn',icon:'linkedin' as IconName,text:'Connect with me professionally.',href:profile.linkedin},{name:'Email',icon:'mail' as IconName,text:'Drop me an email, anytime.',href:`mailto:${profile.email}`}].map(s=><a className="social-option" key={s.name} href={s.href} {...(s.href.startsWith('https')?{target:'_blank',rel:'noopener noreferrer'}:{})}><span className="icon-tile"><Icon name={s.icon} size={25}/></span><span><strong>{s.name}</strong><small>{s.text}</small></span><Icon name="arrow" size={17}/></a>)}</Reveal></div></div></section><CTA title={<>Let’s Create<br/><span className="gradient-text">Impactful Digital Experiences</span></>} description="Whether it’s a web application, a responsive website or a complex business platform — I’m here to help turn your ideas into reality."/></>;}
