import Image from 'next/image';
import Link from 'next/link';
import {profile} from '@/data/portfolio';
import {Icon} from '@/components/icons';
import {CTA,Eyebrow,ResumeButton,Reveal,SectionHeading,SocialLinks,Stats} from '@/components/shared';
import {StoryButton} from '@/components/story';
import {Skills} from '@/components/skills';
import {ProjectGrid} from '@/components/projects';
import {ExperienceTimeline} from '@/components/experience';
import {pageMetadata} from '@/lib/seo';
export const metadata=pageMetadata('Full-Stack Developer & Freelancer','Meet Subrahmanyam Srighakollapu, a full-stack developer building Angular, Next.js, Node.js and .NET products for clients in India and Australia.');
export default function Home(){return <>
  <section className="home-hero dark-section"><div className="hero-light" aria-hidden="true"/><div className="container hero-grid"><div className="home-hero-copy"><div className="availability"><span/>Available for Opportunities</div><p className="hello">Hi, I’m</p><h1><span className="gradient-text">Subrahmanyam<br/>Srighakollapu</span></h1><p className="hero-role">Full-Stack Developer</p><p className="hero-stack">Angular | Next.js | Node.js | .NET | SQL</p><p className="hero-description">I build modern, scalable and user-friendly web applications, HRMS platforms, CMS websites and business dashboards. Passionate about solving real-world problems through technology and creating impactful digital experiences.</p><div className="button-row"><Link href="/projects/" className="button">View My Work<Icon name="arrow"/></Link><StoryButton/></div></div><div className="hero-portrait-wrap" data-parallax><div className="portrait-shape shape-one"/><div className="portrait-shape shape-two"/><Image className="hero-portrait" src="/images/hero-portrait.webp" alt="Subrahmanyam Srighakollapu, full-stack developer" fill sizes="(max-width: 700px) 90vw, 48vw" priority/><span className="handwritten hero-note note-one" aria-hidden="true">Turning<br/>Ideas into<br/>Real Products<br/><span>⤵</span></span><span className="handwritten hero-note note-two" aria-hidden="true">Web Apps<br/>Dashboards<br/>CMS Platforms<br/>and More... ⤵</span><div className="floating-badge years-badge"><strong>3+</strong><span>Years of<br/>Experience</span></div><div className="floating-badge projects-badge"><Icon name="layers" size={28}/><div><strong>11+</strong><span>Live Websites<br/>Delivered</span></div></div></div><div className="hero-contact-strip"><div><span><Icon name="pin" size={17}/>{profile.location}</span><a href={`tel:${profile.phoneHref}`}><Icon name="phone" size={17}/>{profile.phone}</a><a href={`mailto:${profile.email}`}><Icon name="mail" size={17}/>{profile.email}</a></div><SocialLinks/></div></div></section>
  <div className="container floating-stats"><Stats/></div>
  <section className="section home-about"><div className="container about-grid"><Reveal><Eyebrow>About me</Eyebrow><h2>Building Digital<br/>Experiences That<br/>Create <span className="gradient-text">Real Impact</span></h2><p>Full-Stack Developer with professional and independent client experience building responsive web applications, HRMS/recruitment platforms, CMS-driven websites and business dashboards. Hands-on expertise across Angular, Next.js, React, Node.js/Express, .NET, PHP, PostgreSQL/MySQL, REST API integration, authentication and Linux production deployment.</p><p>Delivered 11+ live production websites as a freelancer across 8+ domains including news/media, fintech, real estate, e-commerce, IT services and hospitality, for clients in India and Australia.</p><div className="button-row"><Link className="button" href="/about/">More About Me<Icon name="arrow"/></Link><ResumeButton/></div></Reveal><Reveal className="about-photo-composition" variant="image"><div className="about-photo" data-parallax><Image src="/images/home-about-portrait.webp" alt="Subrahmanyam working on a laptop" fill sizes="(max-width:700px) 90vw, 40vw"/></div><span className="handwritten about-photo-note" aria-hidden="true">Clean Code<br/>Better Products<br/>Happier Users ⤵</span><blockquote><Icon name="quote" size={30}/><span>Passionate about building products that solve real problems.</span></blockquote></Reveal></div></section>
  <section id="skills" className="section skills-section"><div className="container"><SectionHeading eyebrow="Skills" title="Technologies I Work With" description="A wide range of modern technologies to build scalable, secure and high-performance applications."/><Reveal><Skills/></Reveal></div></section>
  <section className="section featured-section"><div className="container"><SectionHeading eyebrow="Featured projects" title="Recent Work & Case Studies" link="View All Projects" href="/projects/"/><Reveal><ProjectGrid featured/></Reveal></div></section>
  <section className="section journey-section"><div className="container"><SectionHeading eyebrow="Experience" title="My Professional Journey" link="View Full Experience" href="/experience/"/><ExperienceTimeline compact/></div></section>
  <CTA variant="desk"/>
  </>;}
