import Image from 'next/image';
import Link from 'next/link';
import type {CSSProperties,ReactNode} from 'react';
import {navigation,profile} from '@/data/portfolio';
import {Icon,type IconName} from './icons';

export function Reveal({children,className='',delay=0,variant='rise'}:{children:ReactNode;className?:string;delay?:number;variant?:string}){return <div data-reveal data-variant={variant} className={`reveal ${className}`} style={{'--reveal-delay':`${delay}ms`} as CSSProperties}>{children}</div>;}
export function Eyebrow({children,dark=false}:{children:ReactNode;dark?:boolean}){return <span className={`eyebrow ${dark?'dark-eyebrow':''}`}>{children}</span>;}
export function SectionHeading({eyebrow,title,description,link,href}:{eyebrow:string;title:ReactNode;description?:string;link?:string;href?:string}){return <Reveal className="section-heading"><div><Eyebrow>{eyebrow}</Eyebrow><h2>{title}</h2></div>{description&&<p>{description}</p>}{link&&href&&<Link className="text-link" href={href}>{link}<Icon name="arrow" size={17}/></Link>}</Reveal>;}
export function ResumeButton({className='button button-outline'}:{className?:string}){return <a className={className} href={profile.resume} download>Download Resume <Icon name="download" size={17}/></a>;}
export function SocialLinks(){return <div className="social-links"><a href={profile.github} aria-label="GitHub profile" target="_blank" rel="noopener noreferrer"><Icon name="github"/></a><a href={profile.linkedin} aria-label="LinkedIn profile" target="_blank" rel="noopener noreferrer"><Icon name="linkedin"/></a><a href={`mailto:${profile.email}`} aria-label="Send an email"><Icon name="mail"/></a></div>;}
export function Stats({dark=false,compact=false,items}:{dark?:boolean;compact?:boolean;items?:{value:string;label:string;icon:IconName;color:string}[]}){const all=items||[{value:'3+',label:'Years Experience',icon:'code' as IconName,color:'blue'},{value:'11+',label:'Live Client Websites',icon:'layers' as IconName,color:'orange'},{value:'8+',label:'Domains Worked',icon:'globe' as IconName,color:'mint'},{value:'100%',label:'Project Ownership',icon:'trophy' as IconName,color:'purple'}];return <div className={`stats ${dark?'stats-dark':''} ${compact?'stats-compact':''}`}>{all.map((s,i)=><Reveal key={s.label} className="stat" delay={i*65}><span className={`icon-tile ${s.color}`}><Icon name={s.icon} size={27}/></span><div><strong>{s.value}</strong><span>{s.label}</span></div></Reveal>)}</div>;}
export function CTA({variant='mountain',title,description}:{variant?:'mountain'|'desk'|'compact';title?:ReactNode;description?:string}){return <section className={`cta cta-${variant}`}>
  {variant!=='compact'&&<div className="cta-art" data-parallax><Image src={`/images/${variant==='desk'?'home-cta':'mountain-cta'}.webp`} alt="" fill sizes="(max-width: 700px) 100vw, 60vw"/></div>}
  <div className="container cta-inner"><Reveal className="cta-copy"><Eyebrow dark>Let’s connect</Eyebrow><h2>{title||<>Let’s Build Something<br/><span className="gradient-text">Amazing Together</span></>}</h2><p>{description||'I’m always open to new opportunities, interesting projects or just having a chat about technology.'}</p><div className="button-row"><Link className="button" href="/contact/">Get in Touch <Icon name="arrow"/></Link>{variant!=='compact'&&<ResumeButton/>}</div></Reveal>{variant!=='compact'&&<p className="handwritten cta-note" aria-hidden="true">New opportunities<br/>Exciting projects<br/>Better solutions<br/>Together ↗</p>}</div>
  </section>;}
export function Footer(){return <footer className="site-footer"><div className="container"><div className="footer-main"><Link href="/" className="brand"><span className="brand-mark" aria-hidden="true">S</span><span><strong>{profile.name}</strong><small>{profile.role}</small></span></Link><nav aria-label="Footer navigation">{navigation.map(n=><Link key={n.label} href={n.href}>{n.label}</Link>)}</nav><SocialLinks/></div><div className="footer-bottom"><p>© {new Date().getFullYear()} {profile.name}. All rights reserved.</p><p>Building reliable digital experiences that make an impact.</p></div></div></footer>;}
